version: '3'

networks:
  schedule_generator:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.4
    volumes:
      - mongo_data:/data/db
    restart: on-failure
  
  frontfacingserver:
    image:  registry.gitlab.com/polytechnique-montr-al/log89xx/23-1/equipe-10/frontfacingserver:test
    ports: 
      - 5000:5000
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.2
    volumes:
      - dataset:/app/dataset
    restart: on-failure
  web_app:
    image: registry.gitlab.com/polytechnique-montr-al/log89xx/23-1/equipe-10/front-end-application:test
    ports:
      - 4200:4200
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.3
    restart: on-failure
    depends_on:
      - frontfacingserver

volumes:
  dataset:
  mongo_data:    

