version: '3'

networks:
  schedule_generator:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.4
    volumes:
      - mongo_data:/data/db
    restart: on-failure

  frontfacingserver:
    build:  frontfacingserver/.
    ports: 
      - 5000:443
      - 5001:5000
    command: >
     bash -c "systemctl start nginx && /venv/bin/python app.py"
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.2
    volumes:
      - dataset:/app/dataset
    restart: on-failure

  web_app:
    build: front-end-application/.
    command: > 
     bash -c "systemctl start nginx && npm start"
    ports:
      - 4200:443
    networks:
      schedule_generator:
        ipv4_address: 192.168.5.3
    restart: on-failure
    depends_on:
      - frontfacingserver

volumes:
  dataset:
  mongo_data: